// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBar7SRqt8CEqwqqBikad0JdtXQpjPa5Mg',
    appId: '1:94871805665:web:d9b1cf4870121648ffa1a0',
    messagingSenderId: '94871805665',
    projectId: 'opportunites-mali-dd0f9',
    authDomain: 'opportunites-mali-dd0f9.firebaseapp.com',
    storageBucket: 'opportunites-mali-dd0f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSCWEKzgmgmarYd2xn5qYErr_H770XtDY',
    appId: '1:94871805665:android:540414e84f469063ffa1a0',
    messagingSenderId: '94871805665',
    projectId: 'opportunites-mali-dd0f9',
    storageBucket: 'opportunites-mali-dd0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fGg0cG9GbVO5i9cbn4U0Bgo1S0KWyBk',
    appId: '1:94871805665:ios:1da649c6abb1f035ffa1a0',
    messagingSenderId: '94871805665',
    projectId: 'opportunites-mali-dd0f9',
    storageBucket: 'opportunites-mali-dd0f9.firebasestorage.app',
    iosBundleId: 'com.example.projet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0fGg0cG9GbVO5i9cbn4U0Bgo1S0KWyBk',
    appId: '1:94871805665:ios:1da649c6abb1f035ffa1a0',
    messagingSenderId: '94871805665',
    projectId: 'opportunites-mali-dd0f9',
    storageBucket: 'opportunites-mali-dd0f9.firebasestorage.app',
    iosBundleId: 'com.example.projet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBar7SRqt8CEqwqqBikad0JdtXQpjPa5Mg',
    appId: '1:94871805665:web:155477c95a51c710ffa1a0',
    messagingSenderId: '94871805665',
    projectId: 'opportunites-mali-dd0f9',
    authDomain: 'opportunites-mali-dd0f9.firebaseapp.com',
    storageBucket: 'opportunites-mali-dd0f9.firebasestorage.app',
  );
}
